### ISSUE TITLE
Project alive?

### ISSUE THREAD

**Issue by breadlesscode** [neos/form-yamlbuilder#1]
Is this project dead? I love the idea of an form builder =)

**Comment by radmiraal** [comment]
Nope, it's not dead. Just doesn't need much maintenance :-)

**Comment by bwaidelich** [comment]
@breadlesscode Do you have issues with the package or why did you open a ticket?
I'll close this for now, but feel free to re-open if you experience any problems.
Regarding your question: The package should work (although it could use a Flow 4.0 compatible version, see #2) but it's not actively maintained
